document.writeln("<!DOCTYPE html>");
document.writeln("<html> ");
document.writeln("<head>");
document.writeln("  <!-- Specifies the character encoding of the document. -->");
document.writeln("  <meta http-equiv=\'content-type\' content=\'text/html; charset=utf-8\' \'>");
document.writeln("");
document.writeln("  <!-- Specifies the title of the document. -->");
document.writeln("  <title>Philip B. Zhang\'s Homepage</title>");
document.writeln("");
document.writeln("  <!-- Global site tag (gtag.js) - Google Analytics -->");
document.writeln("  <script async src=\'https://www.googletagmanager.com/gtag/js?id=UA-132770448-1\'></script>");
document.writeln("  <script>");
document.writeln("    window.dataLayer = window.dataLayer || [];");
document.writeln("    function gtag(){dataLayer.push(arguments);}");
document.writeln("    gtag(\'js\', new Date());");
document.writeln("");
document.writeln("    gtag(\'config\', \'UA-132770448-1\');");
document.writeln("  </script>");
document.writeln("<script src=\'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/latest.js?config=TeX-MML-AM_CHTML\' async></script>");
document.writeln("");
document.writeln("  <!-- Provides the location of the CSS style sheet for the document. -->");
document.writeln("  <link rel=\'stylesheet\' type=\'text/css\' href=\'./stylesheet.css\'>");
document.writeln("</head>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<body>  ");
document.writeln("");
document.writeln("<header>");
document.writeln("        ");
document.writeln("        <div class=\'zzz\'>Philip B. Zhang (张彪) </div>");
document.writeln("        ");
document.writeln("        ");
document.writeln("        <nav>");
document.writeln("            <ul>");
document.writeln("                <li><a href=\'./index.html\'>Home</a></li>");
document.writeln("                <li><a href=\'./research.html\'>Research</a></li>");
document.writeln("                <li><a href=\'./teaching.html\'>Teaching</a></li>");
document.writeln("                <li><a href=\'./chinese.html\' >Chinese Version</a></li>");
document.writeln("            </ul>");
document.writeln("         </nav>");
document.writeln("        ");
document.writeln("  <hr>");
document.writeln("");
document.writeln("    ");
document.writeln("</header>");
document.writeln("");
document.writeln("");
document.writeln("  <br>  <br>");
document.writeln("");
document.writeln("");
document.writeln("</body>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("</html>");
document.writeln("");